version: '3'
services:
  api-service:
    entrypoint:
      [
        "bash",
        "-c",
        "python -m debugpy --listen 0.0.0.0:5678 run_service.py"
      ]
    ports:
      - ${DEBUGPY_EXT_PORT?}:5678
    volumes:
      - ../:/app/