version: '3'
services:
  api-service:
    build:
      context: ../
    profiles:
      - app
    ports:
      - ${API_EXT_PORT?}:8080
    entrypoint:
      [
        "bash",
        "-c",
        "run_service.py"
      ]